/**
 * useAiAnalyzeStream — SSE streaming hook for the /ai/analyze/stream endpoint.
 *
 * Replaces the old useMutation-based analyze flow. The backend now streams
 * the narrative as it's generated by the model, then sends a final `done`
 * event containing the parsed signal. The user sees text appearing live
 * instead of staring at a spinner for 1–2 minutes.
 *
 * Wire format — each SSE frame is `data: <json>\n\n` where the JSON is
 * one of:
 *
 *   {"type": "token", "content": "..."}
 *   {"type": "done",  "session_id": "...",
 *                     "signal": {...} | null,
 *                     "message": "<full narrative>"}
 *
 * The hook drives `streamingContent` while tokens are arriving so the
 * existing chat-bubble streaming UI in AiChatPanel keeps working unchanged.
 * On `done`, it commits the full message + signal + session id and records
 * the elapsed wall time so the response-time badge can pick it up.
 */

import { useCallback, useRef } from "react";
import { useAiStore } from "@/store";
import { useChartStore } from "@/store/chart";
import { API_BASE } from "@/config/endpoints";
import type {
  AIProviderMetadata,
  AiContextMode,
  FibonacciSnapshot,
} from "@/modules/parallax/api";

/* ── Types ── */

export interface AnalyzeStreamRequest {
  conid: number;
  symbol: string;
  timeframes: string[];
  indicators: string[];
  session_id?: string;
  watchlist?: string;
  indicator_priority?: string[];
  context_mode?: AiContextMode;
  context_bars?: number;
}

interface SseTokenEvent {
  type: "token";
  content: string;
}

interface SseDoneEvent {
  type: "done";
  session_id: string;
  signal: unknown; // typed as SignalData on the consuming side
  message: string;
  provider?: AIProviderMetadata;
}

type SseEvent = SseTokenEvent | SseDoneEvent;

/* ── Helpers ── */

function msgId(): string {
  return `msg_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
}

function buildFibSnapshots(): FibonacciSnapshot[] {
  return useChartStore
    .getState()
    .activeFibs
    // Hidden fibs are off the chart, so they're off the analysis too —
    // "what you see is what gets analyzed."
    .filter((fib) => !fib.hidden)
    .map((fib, index) => ({
      source: fib.source,
      swing_high: fib.result.swing_high,
      swing_low: fib.result.swing_low,
      swing_high_time: fib.result.swing_high_time,
      swing_low_time: fib.result.swing_low_time,
      direction: fib.result.direction,
      score: fib.result.score,
      is_primary: index === 0,
      timeframe: null,
    }));
}

/**
 * Parse one SSE `data:` line into a typed event, or null if it's a keep-alive
 * or unparseable frame. We're lenient — bad JSON just gets dropped, so a
 * single corrupt frame can't kill the stream.
 */
function parseEventLine(line: string): SseEvent | null {
  if (!line.startsWith("data: ")) return null;
  const payload = line.slice(6).trim();
  if (!payload) return null;
  try {
    const obj = JSON.parse(payload) as SseEvent;
    if (obj && (obj.type === "token" || obj.type === "done")) return obj;
    return null;
  } catch {
    return null;
  }
}

/* ── Hook ── */

export function useAiAnalyzeStream() {
  const {
    isAnalyzing,
    streamingContent,
    setSessionId,
    addMessage,
    setSignal,
    setAnalyzing,
    setStreaming,
    setStreamingContent,
    appendStreamingContent,
    clearChat,
    pushResponseTime,
    setLastProviderMetadata,
  } = useAiStore();

  const abortRef = useRef<AbortController | null>(null);

  const startAnalyze = useCallback(
    async (req: AnalyzeStreamRequest, model: string | null) => {
      if (isAnalyzing) return;

      // Reset chat — analyze always starts a fresh signal/conversation
      clearChat();
      setAnalyzing(true);
      setStreaming(true);
      setStreamingContent("");

      const controller = new AbortController();
      abortRef.current = controller;
      const startedAt = performance.now();

      try {
        const payload = {
          ...req,
          fibs: buildFibSnapshots(),
        };

        const resp = await fetch(`${API_BASE}/ai/analyze/stream`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(payload),
          signal: controller.signal,
        });

        if (!resp.ok || !resp.body) {
          throw new Error(`Stream request failed: ${resp.status}`);
        }

        const reader = resp.body.getReader();
        const decoder = new TextDecoder();
        let buffer = ""; // partial-line carry-over

        let finalSessionId = req.session_id ?? "";
        let finalSignal: unknown = null;
        let finalMessage = "";
        let finalProviderMetadata: AIProviderMetadata | null = null;
        let sawDone = false;

        // SSE loop — read chunks, split on lines, parse `data: …` frames
        // eslint-disable-next-line no-constant-condition
        while (true) {
          const { done, value } = await reader.read();
          if (done) break;
          buffer += decoder.decode(value, { stream: true });

          const lines = buffer.split("\n");
          buffer = lines.pop() ?? "";

          for (const line of lines) {
            const ev = parseEventLine(line);
            if (!ev) continue;
            if (ev.type === "token") {
              appendStreamingContent(ev.content);
            } else if (ev.type === "done") {
              finalSessionId = ev.session_id;
              finalSignal = ev.signal;
              finalMessage = ev.message;
              finalProviderMetadata = ev.provider ?? null;
              sawDone = true;
            }
          }
        }
        // Flush any trailing complete line in the buffer
        const trailing = parseEventLine(buffer);
        if (trailing?.type === "token") {
          appendStreamingContent(trailing.content);
        } else if (trailing?.type === "done") {
          finalSessionId = trailing.session_id;
          finalSignal = trailing.signal;
          finalMessage = trailing.message;
          finalProviderMetadata = trailing.provider ?? null;
          sawDone = true;
        }

        // Commit final state
        if (finalSessionId) setSessionId(finalSessionId);
        if (sawDone) {
          // Use the authoritative `message` field (the full narrative) — the
          // streamingContent buffer should match, but `message` is what the
          // backend actually parsed the signal from.
          addMessage({
            id: msgId(),
            role: "assistant",
            content: finalMessage || useAiStore.getState().streamingContent,
            timestamp: Date.now(),
          });
          // SignalData typing lives in components/ai — store accepts unknown shape
          setSignal(finalSignal as never);
          setLastProviderMetadata(finalProviderMetadata);
          pushResponseTime({
            durationMs: performance.now() - startedAt,
            model,
            at: Date.now(),
          });
        } else {
          // Stream ended without a done event — surface what we got
          const partial = useAiStore.getState().streamingContent;
          addMessage({
            id: msgId(),
            role: "assistant",
            content:
              partial ||
              "[Analysis stream ended without a final response — try again.]",
            timestamp: Date.now(),
          });
        }
      } catch (err) {
        if ((err as Error).name === "AbortError") {
          const partial = useAiStore.getState().streamingContent;
          if (partial) {
            addMessage({
              id: msgId(),
              role: "assistant",
              content: partial + "\n\n[Cancelled]",
              timestamp: Date.now(),
            });
          }
        } else {
          addMessage({
            id: msgId(),
            role: "assistant",
            content: `[Analysis failed: ${(err as Error).message}]`,
            timestamp: Date.now(),
          });
        }
      } finally {
        setAnalyzing(false);
        setStreaming(false);
        setStreamingContent("");
        abortRef.current = null;
      }
    },
    [
      isAnalyzing, clearChat, setAnalyzing, setStreaming, setStreamingContent,
      appendStreamingContent, addMessage, setSessionId, setSignal,
      setLastProviderMetadata, pushResponseTime,
    ],
  );

  const cancelAnalyze = useCallback(() => {
    abortRef.current?.abort();
  }, []);

  return {
    startAnalyze,
    cancelAnalyze,
    isAnalyzing,
    streamingContent,
  };
}
